### ISSUE TITLE
No sidebar to choose Model.

### ISSUE THREAD

**Issue by lalitaalaalitah** [madtank/OllamaAssist#4]
Installed a virtualenv with pyenv. Python version 3.11. 
Installed requirements.
ran `streamlit run ollama_chatbot.py`
Got this error:

```
 File "/path/to/Github/OllamaAssist/ollama_chatbot.py", line 21, in setup_sidebar
    model = st.selectbox('Choose an LLM?', Config.OLLAMA_MODELS, index=Config.OLLAMA_MODELS.index(Config.DEFAULT_MODEL))
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: tuple.index(x): x not in tuple
```

**Comment by lalitaalaalitah** [comment]
I've changed this to `model = st.selectbox('Choose an LLM?', Config.OLLAMA_MODELS, index=0)` and it works now.

**Comment by madtank** [comment]
Thank you! I'll look at this fix.

**Comment by madtank** [comment]
I think the issue is you don't have the default model that I'm setting llama 3.2 3b. 
So I need to validate first you have the default model, and if not, just use the first in the list.
Thanks!

**Comment by lalitaalaalitah** [comment]
Thanks, I didn't have 3.2:3b. I downloaded it and reverted back to your code, it didn't give any error.
Please, add this is in README, if not already.

**Comment by madtank** [comment]
I'm going to fix it so if you don't have llama3.2 it'll default to first in list. That's a good suggestion to call out in the README, also I can call out how to set default. Thanks!

**Comment by madtank** [comment]
https://github.com/madtank/OllamaAssist/pull/5/files
